EXEC sp_configure 'show advanced options' , 1;  RECONFIGURE WITH OVERRIDE
EXEC sp_configure 'recovery interval (min)' , 0;
EXEC sp_configure 'allow updates' , 0;
EXEC sp_configure 'user connections' , 0;
EXEC sp_configure 'locks' , 0;
EXEC sp_configure 'open objects' , 0;
EXEC sp_configure 'fill factor (%)' , 0;
EXEC sp_configure 'disallow results from triggers' , 0;
EXEC sp_configure 'nested triggers' , 1;
EXEC sp_configure 'server trigger recursion' , 1;
EXEC sp_configure 'remote access' , 1;
EXEC sp_configure 'default language' , 0;
EXEC sp_configure 'cross db ownership chaining' , 0;
EXEC sp_configure 'max worker threads' , 0;
EXEC sp_configure 'network packet size (B)' , 4096;
EXEC sp_configure 'show advanced options' , 1;
EXEC sp_configure 'remote proc trans' , 0;
EXEC sp_configure 'c2 audit mode' , 0;
EXEC sp_configure 'default full-text language' , 1033;
EXEC sp_configure 'two digit year cutoff' , 2049;
EXEC sp_configure 'index create memory (KB)' , 0;
EXEC sp_configure 'priority boost' , 0;
EXEC sp_configure 'remote login timeout (s)' , 10;
EXEC sp_configure 'remote query timeout (s)' , 600;
EXEC sp_configure 'cursor threshold' , -1;
EXEC sp_configure 'set working set size' , 0;
EXEC sp_configure 'user options' , 0;
EXEC sp_configure 'affinity mask' , 0;
EXEC sp_configure 'max text repl size (B)' , 65536;
EXEC sp_configure 'media retention' , 0;
EXEC sp_configure 'cost threshold for parallelism' , 5;
EXEC sp_configure 'max degree of parallelism' , 0;
EXEC sp_configure 'min memory per query (KB)' , 1024;
EXEC sp_configure 'query wait (s)' , -1;
EXEC sp_configure 'min server memory (MB)' , 0;
EXEC sp_configure 'max server memory (MB)' , 2147483647;
EXEC sp_configure 'query governor cost limit' , 0;
EXEC sp_configure 'lightweight pooling' , 0;
EXEC sp_configure 'scan for startup procs' , 0;
EXEC sp_configure 'affinity64 mask' , 0;
EXEC sp_configure 'affinity I/O mask' , 0;
EXEC sp_configure 'affinity64 I/O mask' , 0;
EXEC sp_configure 'transform noise words' , 0;
EXEC sp_configure 'precompute rank' , 0;
EXEC sp_configure 'PH timeout (s)' , 60;
EXEC sp_configure 'clr enabled' , 0;
EXEC sp_configure 'max full-text crawl range' , 4;
EXEC sp_configure 'ft notify bandwidth (min)' , 0;
EXEC sp_configure 'ft notify bandwidth (max)' , 100;
EXEC sp_configure 'ft crawl bandwidth (min)' , 0;
EXEC sp_configure 'ft crawl bandwidth (max)' , 100;
EXEC sp_configure 'default trace enabled' , 1;
EXEC sp_configure 'blocked process threshold (s)' , 0;
EXEC sp_configure 'in-doubt xact resolution' , 0;
EXEC sp_configure 'remote admin connections' , 0;
EXEC sp_configure 'common criteria compliance enabled' , 0;
EXEC sp_configure 'EKM provider enabled' , 0;
EXEC sp_configure 'backup compression default' , 0;
EXEC sp_configure 'filestream access level' , 0;
EXEC sp_configure 'optimize for ad hoc workloads' , 0;
EXEC sp_configure 'access check cache bucket count' , 0;
EXEC sp_configure 'access check cache quota' , 0;
EXEC sp_configure 'backup checksum default' , 0;
EXEC sp_configure 'automatic soft-NUMA disabled' , 0;
EXEC sp_configure 'external scripts enabled' , 0;
EXEC sp_configure 'clr strict security' , 1;
EXEC sp_configure 'column encryption enclave type' , 0;
EXEC sp_configure 'tempdb metadata memory-optimized' , 0;
EXEC sp_configure 'Agent XPs' , 0;
EXEC sp_configure 'Database Mail XPs' , 0;
EXEC sp_configure 'SMO and DMO XPs' , 1;
EXEC sp_configure 'Ole Automation Procedures' , 0;
EXEC sp_configure 'xp_cmdshell' , 0;
EXEC sp_configure 'Ad Hoc Distributed Queries' , 0;
EXEC sp_configure 'Replication XPs' , 0;
EXEC sp_configure 'contained database authentication' , 0;
EXEC sp_configure 'hadoop connectivity' , 0;
EXEC sp_configure 'polybase network encryption' , 1;
EXEC sp_configure 'remote data archive' , 0;
EXEC sp_configure 'allow polybase export' , 0;
EXEC sp_configure 'allow filesystem enumeration' , 1;
EXEC sp_configure 'polybase enabled' , 0;
EXEC sp_configure 'show advanced options' , 0;
RECONFIGURE WITH OVERRIDE
