/*
	Created by POMFPC\jpomf using dbatools Export-DbaScript for objects on mssql2 at 09/29/2019 20:07:21
	See https://dbatools.io/Export-DbaScript for more information
*/
ALTER RESOURCE GOVERNOR WITH (CLASSIFIER_FUNCTION = NULL);
ALTER RESOURCE GOVERNOR WITH (MAX_OUTSTANDING_IO_PER_VOLUME = DEFAULT);
ALTER RESOURCE GOVERNOR RECONFIGURE;
ALTER RESOURCE GOVERNOR DISABLE;
ALTER RESOURCE GOVERNOR RECONFIGURE
